GET http://localhost:3000/notes

###

GET http://localhost:3000/notes/6500d9093638ca859793d418

###

POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "My third note",
    "content": "If you want, you can!"
}

###

DELETE http://localhost:3000/notes/6500c8fc7aa2e0169fb22012

###
PATCH http://localhost:3000/notes/6500e60067f9dc62d9f30dea
Content-Type: application/json

{
    "title": "My third UPDATED note"
}
